// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auto_catalog.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateCarModelRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCarModelRequest) Reset()         { *m = CreateCarModelRequest{} }
func (m *CreateCarModelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCarModelRequest) ProtoMessage()    {}
func (*CreateCarModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{0}
}

func (m *CreateCarModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCarModelRequest.Unmarshal(m, b)
}
func (m *CreateCarModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCarModelRequest.Marshal(b, m, deterministic)
}
func (m *CreateCarModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCarModelRequest.Merge(m, src)
}
func (m *CreateCarModelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCarModelRequest.Size(m)
}
func (m *CreateCarModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCarModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCarModelRequest proto.InternalMessageInfo

func (m *CreateCarModelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CarModel struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarModel) Reset()         { *m = CarModel{} }
func (m *CarModel) String() string { return proto.CompactTextString(m) }
func (*CarModel) ProtoMessage()    {}
func (*CarModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{1}
}

func (m *CarModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarModel.Unmarshal(m, b)
}
func (m *CarModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarModel.Marshal(b, m, deterministic)
}
func (m *CarModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarModel.Merge(m, src)
}
func (m *CarModel) XXX_Size() int {
	return xxx_messageInfo_CarModel.Size(m)
}
func (m *CarModel) XXX_DiscardUnknown() {
	xxx_messageInfo_CarModel.DiscardUnknown(m)
}

var xxx_messageInfo_CarModel proto.InternalMessageInfo

func (m *CarModel) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CarModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetCarModelByIdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCarModelByIdRequest) Reset()         { *m = GetCarModelByIdRequest{} }
func (m *GetCarModelByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetCarModelByIdRequest) ProtoMessage()    {}
func (*GetCarModelByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{2}
}

func (m *GetCarModelByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarModelByIdRequest.Unmarshal(m, b)
}
func (m *GetCarModelByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarModelByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetCarModelByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarModelByIdRequest.Merge(m, src)
}
func (m *GetCarModelByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetCarModelByIdRequest.Size(m)
}
func (m *GetCarModelByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarModelByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarModelByIdRequest proto.InternalMessageInfo

func (m *GetCarModelByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListCarModelsResponse struct {
	Items                []*CarModel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCarModelsResponse) Reset()         { *m = ListCarModelsResponse{} }
func (m *ListCarModelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCarModelsResponse) ProtoMessage()    {}
func (*ListCarModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{3}
}

func (m *ListCarModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCarModelsResponse.Unmarshal(m, b)
}
func (m *ListCarModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCarModelsResponse.Marshal(b, m, deterministic)
}
func (m *ListCarModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCarModelsResponse.Merge(m, src)
}
func (m *ListCarModelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCarModelsResponse.Size(m)
}
func (m *ListCarModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCarModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCarModelsResponse proto.InternalMessageInfo

func (m *ListCarModelsResponse) GetItems() []*CarModel {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteCarModelRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCarModelRequest) Reset()         { *m = DeleteCarModelRequest{} }
func (m *DeleteCarModelRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCarModelRequest) ProtoMessage()    {}
func (*DeleteCarModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{4}
}

func (m *DeleteCarModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCarModelRequest.Unmarshal(m, b)
}
func (m *DeleteCarModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCarModelRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCarModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCarModelRequest.Merge(m, src)
}
func (m *DeleteCarModelRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCarModelRequest.Size(m)
}
func (m *DeleteCarModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCarModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCarModelRequest proto.InternalMessageInfo

func (m *DeleteCarModelRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateComponentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CarModelId           int32    `protobuf:"varint,2,opt,name=car_model_id,json=carModelId,proto3" json:"car_model_id,omitempty"`
	ParentId             int32    `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateComponentRequest) Reset()         { *m = CreateComponentRequest{} }
func (m *CreateComponentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateComponentRequest) ProtoMessage()    {}
func (*CreateComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{5}
}

func (m *CreateComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateComponentRequest.Unmarshal(m, b)
}
func (m *CreateComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateComponentRequest.Marshal(b, m, deterministic)
}
func (m *CreateComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateComponentRequest.Merge(m, src)
}
func (m *CreateComponentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateComponentRequest.Size(m)
}
func (m *CreateComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateComponentRequest proto.InternalMessageInfo

func (m *CreateComponentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateComponentRequest) GetCarModelId() int32 {
	if m != nil {
		return m.CarModelId
	}
	return 0
}

func (m *CreateComponentRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type Component struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CarModelId           int32    `protobuf:"varint,3,opt,name=car_model_id,json=carModelId,proto3" json:"car_model_id,omitempty"`
	ParentId             int32    `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{6}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetCarModelId() int32 {
	if m != nil {
		return m.CarModelId
	}
	return 0
}

func (m *Component) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type ListComponentResponse struct {
	Items                []*Component `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListComponentResponse) Reset()         { *m = ListComponentResponse{} }
func (m *ListComponentResponse) String() string { return proto.CompactTextString(m) }
func (*ListComponentResponse) ProtoMessage()    {}
func (*ListComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{7}
}

func (m *ListComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListComponentResponse.Unmarshal(m, b)
}
func (m *ListComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListComponentResponse.Marshal(b, m, deterministic)
}
func (m *ListComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListComponentResponse.Merge(m, src)
}
func (m *ListComponentResponse) XXX_Size() int {
	return xxx_messageInfo_ListComponentResponse.Size(m)
}
func (m *ListComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListComponentResponse proto.InternalMessageInfo

func (m *ListComponentResponse) GetItems() []*Component {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetTopLevelComponentsByCarModelRequest struct {
	CarModelId           int32    `protobuf:"varint,1,opt,name=car_model_id,json=carModelId,proto3" json:"car_model_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopLevelComponentsByCarModelRequest) Reset() {
	*m = GetTopLevelComponentsByCarModelRequest{}
}
func (m *GetTopLevelComponentsByCarModelRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopLevelComponentsByCarModelRequest) ProtoMessage()    {}
func (*GetTopLevelComponentsByCarModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{8}
}

func (m *GetTopLevelComponentsByCarModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Unmarshal(m, b)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Marshal(b, m, deterministic)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Merge(m, src)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Size(m)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopLevelComponentsByCarModelRequest proto.InternalMessageInfo

func (m *GetTopLevelComponentsByCarModelRequest) GetCarModelId() int32 {
	if m != nil {
		return m.CarModelId
	}
	return 0
}

type GetChildComponentsByComponentRequest struct {
	ParentId             int32    `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChildComponentsByComponentRequest) Reset()         { *m = GetChildComponentsByComponentRequest{} }
func (m *GetChildComponentsByComponentRequest) String() string { return proto.CompactTextString(m) }
func (*GetChildComponentsByComponentRequest) ProtoMessage()    {}
func (*GetChildComponentsByComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{9}
}

func (m *GetChildComponentsByComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChildComponentsByComponentRequest.Unmarshal(m, b)
}
func (m *GetChildComponentsByComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChildComponentsByComponentRequest.Marshal(b, m, deterministic)
}
func (m *GetChildComponentsByComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChildComponentsByComponentRequest.Merge(m, src)
}
func (m *GetChildComponentsByComponentRequest) XXX_Size() int {
	return xxx_messageInfo_GetChildComponentsByComponentRequest.Size(m)
}
func (m *GetChildComponentsByComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChildComponentsByComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChildComponentsByComponentRequest proto.InternalMessageInfo

func (m *GetChildComponentsByComponentRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type DeleteComponentRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteComponentRequest) Reset()         { *m = DeleteComponentRequest{} }
func (m *DeleteComponentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteComponentRequest) ProtoMessage()    {}
func (*DeleteComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{10}
}

func (m *DeleteComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteComponentRequest.Unmarshal(m, b)
}
func (m *DeleteComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteComponentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteComponentRequest.Merge(m, src)
}
func (m *DeleteComponentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteComponentRequest.Size(m)
}
func (m *DeleteComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteComponentRequest proto.InternalMessageInfo

func (m *DeleteComponentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateComponentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateComponentRequest) Reset()         { *m = UpdateComponentRequest{} }
func (m *UpdateComponentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateComponentRequest) ProtoMessage()    {}
func (*UpdateComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{11}
}

func (m *UpdateComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateComponentRequest.Unmarshal(m, b)
}
func (m *UpdateComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateComponentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateComponentRequest.Merge(m, src)
}
func (m *UpdateComponentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateComponentRequest.Size(m)
}
func (m *UpdateComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateComponentRequest proto.InternalMessageInfo

func (m *UpdateComponentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b2b0ccfa0821d94, []int{12}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateCarModelRequest)(nil), "api.CreateCarModelRequest")
	proto.RegisterType((*CarModel)(nil), "api.CarModel")
	proto.RegisterType((*GetCarModelByIdRequest)(nil), "api.GetCarModelByIdRequest")
	proto.RegisterType((*ListCarModelsResponse)(nil), "api.ListCarModelsResponse")
	proto.RegisterType((*DeleteCarModelRequest)(nil), "api.DeleteCarModelRequest")
	proto.RegisterType((*CreateComponentRequest)(nil), "api.CreateComponentRequest")
	proto.RegisterType((*Component)(nil), "api.Component")
	proto.RegisterType((*ListComponentResponse)(nil), "api.ListComponentResponse")
	proto.RegisterType((*GetTopLevelComponentsByCarModelRequest)(nil), "api.GetTopLevelComponentsByCarModelRequest")
	proto.RegisterType((*GetChildComponentsByComponentRequest)(nil), "api.GetChildComponentsByComponentRequest")
	proto.RegisterType((*DeleteComponentRequest)(nil), "api.DeleteComponentRequest")
	proto.RegisterType((*UpdateComponentRequest)(nil), "api.UpdateComponentRequest")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

func init() { proto.RegisterFile("auto_catalog.proto", fileDescriptor_6b2b0ccfa0821d94) }

var fileDescriptor_6b2b0ccfa0821d94 = []byte{
	// 494 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0x1a, 0x9a, 0x81, 0x26, 0xd2, 0x48, 0x89, 0x2a, 0x57, 0x88, 0x68, 0xa9, 0x20,
	0xa8, 0x28, 0x87, 0x72, 0x02, 0xb5, 0x02, 0x1a, 0x50, 0x15, 0x54, 0x2e, 0x06, 0xce, 0xd1, 0x92,
	0x1d, 0xd1, 0x15, 0xb6, 0x77, 0xb1, 0x37, 0x95, 0xf2, 0x41, 0xfc, 0x27, 0x8a, 0xbd, 0x31, 0xf1,
	0xda, 0x6a, 0xc2, 0x2d, 0xca, 0xcc, 0xce, 0xbc, 0xf7, 0xe6, 0x3d, 0x03, 0xf2, 0xa5, 0x51, 0xf3,
	0x05, 0x37, 0x3c, 0x52, 0x3f, 0x27, 0x3a, 0x55, 0x46, 0x61, 0x87, 0x6b, 0xc9, 0xce, 0x60, 0x30,
	0x4d, 0x89, 0x1b, 0x9a, 0xf2, 0xf4, 0x8b, 0x12, 0x14, 0x85, 0xf4, 0x7b, 0x49, 0x99, 0x41, 0x84,
	0x83, 0x84, 0xc7, 0x74, 0xec, 0x8d, 0xbc, 0x71, 0x37, 0xcc, 0x7f, 0xb3, 0x09, 0x1c, 0x6e, 0xda,
	0xb0, 0x07, 0x6d, 0x29, 0xf2, 0xaa, 0x1f, 0xb6, 0xa5, 0x28, 0xfb, 0xdb, 0x5b, 0xfd, 0x63, 0x18,
	0x5e, 0x93, 0xd9, 0x3c, 0xb9, 0x5a, 0xcd, 0xc4, 0x66, 0xba, 0xf3, 0x9a, 0x5d, 0xc0, 0xe0, 0x46,
	0x66, 0x65, 0x6b, 0x16, 0x52, 0xa6, 0x55, 0x92, 0x11, 0x3e, 0x03, 0x5f, 0x1a, 0x8a, 0xb3, 0x63,
	0x6f, 0xd4, 0x19, 0x3f, 0x3a, 0x3f, 0x9a, 0x70, 0x2d, 0x27, 0x25, 0xd6, 0xa2, 0xc6, 0x5e, 0xc0,
	0xe0, 0x23, 0x45, 0x54, 0x27, 0xe1, 0xae, 0xf9, 0x05, 0x43, 0xcb, 0x56, 0xc5, 0x5a, 0x25, 0x94,
	0x98, 0x7b, 0xe8, 0xe2, 0x08, 0x1e, 0x2f, 0x78, 0x3a, 0x8f, 0xd7, 0x13, 0xe7, 0x52, 0xe4, 0xd4,
	0xfc, 0x10, 0x16, 0x76, 0xc9, 0x4c, 0xe0, 0x09, 0x74, 0x35, 0x4f, 0x29, 0x31, 0xeb, 0xf2, 0x41,
	0x5e, 0x3e, 0x2c, 0xfe, 0x98, 0x09, 0x96, 0x40, 0xb7, 0x5c, 0xb3, 0x8f, 0x5c, 0xb5, 0x7d, 0x9d,
	0xff, 0xdb, 0x77, 0x69, 0x35, 0xfc, 0x47, 0xcd, 0x6a, 0x78, 0x5a, 0xd5, 0xb0, 0x57, 0x68, 0x58,
	0xb6, 0x59, 0x11, 0x3f, 0xc3, 0xf3, 0x6b, 0x32, 0xdf, 0x94, 0xbe, 0xa1, 0x3b, 0x8a, 0xca, 0x72,
	0x76, 0xb5, 0x72, 0x55, 0x75, 0x71, 0x7a, 0x2e, 0x4e, 0x36, 0x85, 0xd3, 0xf5, 0xe1, 0x6f, 0x65,
	0x24, 0x2a, 0x83, 0x5c, 0xd5, 0x2b, 0x7c, 0x3c, 0x87, 0xcf, 0x18, 0x86, 0xf6, 0xaa, 0xee, 0x33,
	0xf7, 0xac, 0xaf, 0x60, 0xf8, 0x5d, 0x8b, 0x3d, 0xcf, 0xca, 0x1e, 0x82, 0xff, 0x29, 0xd6, 0x66,
	0x75, 0xfe, 0xc7, 0x07, 0xfc, 0xb0, 0x34, 0x6a, 0x5a, 0xc4, 0xe2, 0x2b, 0xa5, 0x77, 0x72, 0x41,
	0x78, 0x09, 0xbd, 0x6a, 0x24, 0x30, 0x28, 0x14, 0x6b, 0xca, 0x49, 0x50, 0x75, 0x24, 0x6b, 0xe1,
	0x3b, 0xe8, 0x3b, 0xa6, 0xc7, 0x93, 0xbc, 0xa7, 0x39, 0x0a, 0xf5, 0x01, 0x6f, 0xe0, 0xa8, 0x92,
	0x05, 0x84, 0xbc, 0x23, 0xc7, 0x1c, 0x14, 0x50, 0x1a, 0xb3, 0xc2, 0x5a, 0xf8, 0x16, 0x7a, 0xd5,
	0x20, 0x58, 0xe8, 0x8d, 0xe9, 0x08, 0xb6, 0xe6, 0xb2, 0x16, 0xbe, 0x87, 0xbe, 0x93, 0x0d, 0x8b,
	0xbb, 0x39, 0x31, 0x81, 0x63, 0x23, 0xd6, 0xc2, 0x08, 0x9e, 0xee, 0x70, 0x10, 0x9e, 0x6d, 0x94,
	0xd8, 0xc3, 0x67, 0xdb, 0x5c, 0x5d, 0x4f, 0xb3, 0x16, 0xde, 0xc2, 0x93, 0x7b, 0x3d, 0x86, 0x2f,
	0x4b, 0xd5, 0x77, 0xf9, 0x70, 0xc7, 0xa6, 0x0b, 0xe8, 0x3b, 0x46, 0xb4, 0xca, 0x34, 0xdb, 0xb3,
	0xae, 0xab, 0x63, 0x4e, 0xfb, 0xba, 0xd9, 0xb2, 0x75, 0x5d, 0x7f, 0x3c, 0xc8, 0xbf, 0xd7, 0xaf,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xd7, 0xb7, 0x11, 0xc5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AutoCatalogServiceClient is the client API for AutoCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AutoCatalogServiceClient interface {
	CreateCarModel(ctx context.Context, in *CreateCarModelRequest, opts ...grpc.CallOption) (*CarModel, error)
	GetCarModelById(ctx context.Context, in *GetCarModelByIdRequest, opts ...grpc.CallOption) (*CarModel, error)
	ListCarModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCarModelsResponse, error)
	DeleteCarModel(ctx context.Context, in *DeleteCarModelRequest, opts ...grpc.CallOption) (*Empty, error)
	CreateComponent(ctx context.Context, in *CreateComponentRequest, opts ...grpc.CallOption) (*Component, error)
	GetTopLevelComponentsByCarModel(ctx context.Context, in *GetTopLevelComponentsByCarModelRequest, opts ...grpc.CallOption) (*ListComponentResponse, error)
	GetChildComponentsByComponent(ctx context.Context, in *GetChildComponentsByComponentRequest, opts ...grpc.CallOption) (*ListComponentResponse, error)
	DeleteComponent(ctx context.Context, in *DeleteComponentRequest, opts ...grpc.CallOption) (*Empty, error)
	UpdateComponent(ctx context.Context, in *UpdateComponentRequest, opts ...grpc.CallOption) (*Component, error)
}

type autoCatalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewAutoCatalogServiceClient(cc *grpc.ClientConn) AutoCatalogServiceClient {
	return &autoCatalogServiceClient{cc}
}

func (c *autoCatalogServiceClient) CreateCarModel(ctx context.Context, in *CreateCarModelRequest, opts ...grpc.CallOption) (*CarModel, error) {
	out := new(CarModel)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/CreateCarModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) GetCarModelById(ctx context.Context, in *GetCarModelByIdRequest, opts ...grpc.CallOption) (*CarModel, error) {
	out := new(CarModel)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/GetCarModelById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) ListCarModels(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCarModelsResponse, error) {
	out := new(ListCarModelsResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/ListCarModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) DeleteCarModel(ctx context.Context, in *DeleteCarModelRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/DeleteCarModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) CreateComponent(ctx context.Context, in *CreateComponentRequest, opts ...grpc.CallOption) (*Component, error) {
	out := new(Component)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/CreateComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) GetTopLevelComponentsByCarModel(ctx context.Context, in *GetTopLevelComponentsByCarModelRequest, opts ...grpc.CallOption) (*ListComponentResponse, error) {
	out := new(ListComponentResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/GetTopLevelComponentsByCarModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) GetChildComponentsByComponent(ctx context.Context, in *GetChildComponentsByComponentRequest, opts ...grpc.CallOption) (*ListComponentResponse, error) {
	out := new(ListComponentResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/GetChildComponentsByComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) DeleteComponent(ctx context.Context, in *DeleteComponentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/DeleteComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) UpdateComponent(ctx context.Context, in *UpdateComponentRequest, opts ...grpc.CallOption) (*Component, error) {
	out := new(Component)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/UpdateComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoCatalogServiceServer is the server API for AutoCatalogService service.
type AutoCatalogServiceServer interface {
	CreateCarModel(context.Context, *CreateCarModelRequest) (*CarModel, error)
	GetCarModelById(context.Context, *GetCarModelByIdRequest) (*CarModel, error)
	ListCarModels(context.Context, *Empty) (*ListCarModelsResponse, error)
	DeleteCarModel(context.Context, *DeleteCarModelRequest) (*Empty, error)
	CreateComponent(context.Context, *CreateComponentRequest) (*Component, error)
	GetTopLevelComponentsByCarModel(context.Context, *GetTopLevelComponentsByCarModelRequest) (*ListComponentResponse, error)
	GetChildComponentsByComponent(context.Context, *GetChildComponentsByComponentRequest) (*ListComponentResponse, error)
	DeleteComponent(context.Context, *DeleteComponentRequest) (*Empty, error)
	UpdateComponent(context.Context, *UpdateComponentRequest) (*Component, error)
}

// UnimplementedAutoCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAutoCatalogServiceServer struct {
}

func (*UnimplementedAutoCatalogServiceServer) CreateCarModel(ctx context.Context, req *CreateCarModelRequest) (*CarModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCarModel not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) GetCarModelById(ctx context.Context, req *GetCarModelByIdRequest) (*CarModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCarModelById not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) ListCarModels(ctx context.Context, req *Empty) (*ListCarModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCarModels not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) DeleteCarModel(ctx context.Context, req *DeleteCarModelRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCarModel not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) CreateComponent(ctx context.Context, req *CreateComponentRequest) (*Component, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComponent not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) GetTopLevelComponentsByCarModel(ctx context.Context, req *GetTopLevelComponentsByCarModelRequest) (*ListComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopLevelComponentsByCarModel not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) GetChildComponentsByComponent(ctx context.Context, req *GetChildComponentsByComponentRequest) (*ListComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildComponentsByComponent not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) DeleteComponent(ctx context.Context, req *DeleteComponentRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComponent not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) UpdateComponent(ctx context.Context, req *UpdateComponentRequest) (*Component, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComponent not implemented")
}

func RegisterAutoCatalogServiceServer(s *grpc.Server, srv AutoCatalogServiceServer) {
	s.RegisterService(&_AutoCatalogService_serviceDesc, srv)
}

func _AutoCatalogService_CreateCarModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCarModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).CreateCarModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/CreateCarModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).CreateCarModel(ctx, req.(*CreateCarModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_GetCarModelById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarModelByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).GetCarModelById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/GetCarModelById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).GetCarModelById(ctx, req.(*GetCarModelByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_ListCarModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).ListCarModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/ListCarModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).ListCarModels(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_DeleteCarModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCarModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).DeleteCarModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/DeleteCarModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).DeleteCarModel(ctx, req.(*DeleteCarModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_CreateComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).CreateComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/CreateComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).CreateComponent(ctx, req.(*CreateComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_GetTopLevelComponentsByCarModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopLevelComponentsByCarModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).GetTopLevelComponentsByCarModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/GetTopLevelComponentsByCarModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).GetTopLevelComponentsByCarModel(ctx, req.(*GetTopLevelComponentsByCarModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_GetChildComponentsByComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildComponentsByComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).GetChildComponentsByComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/GetChildComponentsByComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).GetChildComponentsByComponent(ctx, req.(*GetChildComponentsByComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_DeleteComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).DeleteComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/DeleteComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).DeleteComponent(ctx, req.(*DeleteComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_UpdateComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).UpdateComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/UpdateComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).UpdateComponent(ctx, req.(*UpdateComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutoCatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AutoCatalogService",
	HandlerType: (*AutoCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCarModel",
			Handler:    _AutoCatalogService_CreateCarModel_Handler,
		},
		{
			MethodName: "GetCarModelById",
			Handler:    _AutoCatalogService_GetCarModelById_Handler,
		},
		{
			MethodName: "ListCarModels",
			Handler:    _AutoCatalogService_ListCarModels_Handler,
		},
		{
			MethodName: "DeleteCarModel",
			Handler:    _AutoCatalogService_DeleteCarModel_Handler,
		},
		{
			MethodName: "CreateComponent",
			Handler:    _AutoCatalogService_CreateComponent_Handler,
		},
		{
			MethodName: "GetTopLevelComponentsByCarModel",
			Handler:    _AutoCatalogService_GetTopLevelComponentsByCarModel_Handler,
		},
		{
			MethodName: "GetChildComponentsByComponent",
			Handler:    _AutoCatalogService_GetChildComponentsByComponent_Handler,
		},
		{
			MethodName: "DeleteComponent",
			Handler:    _AutoCatalogService_DeleteComponent_Handler,
		},
		{
			MethodName: "UpdateComponent",
			Handler:    _AutoCatalogService_UpdateComponent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auto_catalog.proto",
}
