// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auto_reference_catalog.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CarModel struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarModel) Reset()         { *m = CarModel{} }
func (m *CarModel) String() string { return proto.CompactTextString(m) }
func (*CarModel) ProtoMessage()    {}
func (*CarModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{0}
}

func (m *CarModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarModel.Unmarshal(m, b)
}
func (m *CarModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarModel.Marshal(b, m, deterministic)
}
func (m *CarModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarModel.Merge(m, src)
}
func (m *CarModel) XXX_Size() int {
	return xxx_messageInfo_CarModel.Size(m)
}
func (m *CarModel) XXX_DiscardUnknown() {
	xxx_messageInfo_CarModel.DiscardUnknown(m)
}

var xxx_messageInfo_CarModel proto.InternalMessageInfo

func (m *CarModel) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CarModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Component struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CarModelId           int32    `protobuf:"varint,3,opt,name=car_model_id,json=carModelId,proto3" json:"car_model_id,omitempty"`
	ParentId             int32    `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{1}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetCarModelId() int32 {
	if m != nil {
		return m.CarModelId
	}
	return 0
}

func (m *Component) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type CreateCarModelRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCarModelRequest) Reset()         { *m = CreateCarModelRequest{} }
func (m *CreateCarModelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCarModelRequest) ProtoMessage()    {}
func (*CreateCarModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{2}
}

func (m *CreateCarModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCarModelRequest.Unmarshal(m, b)
}
func (m *CreateCarModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCarModelRequest.Marshal(b, m, deterministic)
}
func (m *CreateCarModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCarModelRequest.Merge(m, src)
}
func (m *CreateCarModelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCarModelRequest.Size(m)
}
func (m *CreateCarModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCarModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCarModelRequest proto.InternalMessageInfo

func (m *CreateCarModelRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateCarModelResponse struct {
	Result               *CarModel `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCarModelResponse) Reset()         { *m = CreateCarModelResponse{} }
func (m *CreateCarModelResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCarModelResponse) ProtoMessage()    {}
func (*CreateCarModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{3}
}

func (m *CreateCarModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCarModelResponse.Unmarshal(m, b)
}
func (m *CreateCarModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCarModelResponse.Marshal(b, m, deterministic)
}
func (m *CreateCarModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCarModelResponse.Merge(m, src)
}
func (m *CreateCarModelResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCarModelResponse.Size(m)
}
func (m *CreateCarModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCarModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCarModelResponse proto.InternalMessageInfo

func (m *CreateCarModelResponse) GetResult() *CarModel {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetCarModelByIdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCarModelByIdRequest) Reset()         { *m = GetCarModelByIdRequest{} }
func (m *GetCarModelByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetCarModelByIdRequest) ProtoMessage()    {}
func (*GetCarModelByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{4}
}

func (m *GetCarModelByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarModelByIdRequest.Unmarshal(m, b)
}
func (m *GetCarModelByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarModelByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetCarModelByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarModelByIdRequest.Merge(m, src)
}
func (m *GetCarModelByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetCarModelByIdRequest.Size(m)
}
func (m *GetCarModelByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarModelByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarModelByIdRequest proto.InternalMessageInfo

func (m *GetCarModelByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetCarModelResponse struct {
	Result               *CarModel `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCarModelResponse) Reset()         { *m = GetCarModelResponse{} }
func (m *GetCarModelResponse) String() string { return proto.CompactTextString(m) }
func (*GetCarModelResponse) ProtoMessage()    {}
func (*GetCarModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{5}
}

func (m *GetCarModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCarModelResponse.Unmarshal(m, b)
}
func (m *GetCarModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCarModelResponse.Marshal(b, m, deterministic)
}
func (m *GetCarModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCarModelResponse.Merge(m, src)
}
func (m *GetCarModelResponse) XXX_Size() int {
	return xxx_messageInfo_GetCarModelResponse.Size(m)
}
func (m *GetCarModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCarModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCarModelResponse proto.InternalMessageInfo

func (m *GetCarModelResponse) GetResult() *CarModel {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListCarModelsRequst struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCarModelsRequst) Reset()         { *m = ListCarModelsRequst{} }
func (m *ListCarModelsRequst) String() string { return proto.CompactTextString(m) }
func (*ListCarModelsRequst) ProtoMessage()    {}
func (*ListCarModelsRequst) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{6}
}

func (m *ListCarModelsRequst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCarModelsRequst.Unmarshal(m, b)
}
func (m *ListCarModelsRequst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCarModelsRequst.Marshal(b, m, deterministic)
}
func (m *ListCarModelsRequst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCarModelsRequst.Merge(m, src)
}
func (m *ListCarModelsRequst) XXX_Size() int {
	return xxx_messageInfo_ListCarModelsRequst.Size(m)
}
func (m *ListCarModelsRequst) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCarModelsRequst.DiscardUnknown(m)
}

var xxx_messageInfo_ListCarModelsRequst proto.InternalMessageInfo

type ListCarModelsResponse struct {
	Result               []*CarModel `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCarModelsResponse) Reset()         { *m = ListCarModelsResponse{} }
func (m *ListCarModelsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCarModelsResponse) ProtoMessage()    {}
func (*ListCarModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{7}
}

func (m *ListCarModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCarModelsResponse.Unmarshal(m, b)
}
func (m *ListCarModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCarModelsResponse.Marshal(b, m, deterministic)
}
func (m *ListCarModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCarModelsResponse.Merge(m, src)
}
func (m *ListCarModelsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCarModelsResponse.Size(m)
}
func (m *ListCarModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCarModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCarModelsResponse proto.InternalMessageInfo

func (m *ListCarModelsResponse) GetResult() []*CarModel {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteCarModelRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCarModelRequest) Reset()         { *m = DeleteCarModelRequest{} }
func (m *DeleteCarModelRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCarModelRequest) ProtoMessage()    {}
func (*DeleteCarModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{8}
}

func (m *DeleteCarModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCarModelRequest.Unmarshal(m, b)
}
func (m *DeleteCarModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCarModelRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCarModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCarModelRequest.Merge(m, src)
}
func (m *DeleteCarModelRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCarModelRequest.Size(m)
}
func (m *DeleteCarModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCarModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCarModelRequest proto.InternalMessageInfo

func (m *DeleteCarModelRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteCarModelResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCarModelResponse) Reset()         { *m = DeleteCarModelResponse{} }
func (m *DeleteCarModelResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCarModelResponse) ProtoMessage()    {}
func (*DeleteCarModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{9}
}

func (m *DeleteCarModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCarModelResponse.Unmarshal(m, b)
}
func (m *DeleteCarModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCarModelResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCarModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCarModelResponse.Merge(m, src)
}
func (m *DeleteCarModelResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCarModelResponse.Size(m)
}
func (m *DeleteCarModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCarModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCarModelResponse proto.InternalMessageInfo

type CreateComponentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CarModelId           int32    `protobuf:"varint,2,opt,name=car_model_id,json=carModelId,proto3" json:"car_model_id,omitempty"`
	ParentId             int32    `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateComponentRequest) Reset()         { *m = CreateComponentRequest{} }
func (m *CreateComponentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateComponentRequest) ProtoMessage()    {}
func (*CreateComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{10}
}

func (m *CreateComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateComponentRequest.Unmarshal(m, b)
}
func (m *CreateComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateComponentRequest.Marshal(b, m, deterministic)
}
func (m *CreateComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateComponentRequest.Merge(m, src)
}
func (m *CreateComponentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateComponentRequest.Size(m)
}
func (m *CreateComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateComponentRequest proto.InternalMessageInfo

func (m *CreateComponentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateComponentRequest) GetCarModelId() int32 {
	if m != nil {
		return m.CarModelId
	}
	return 0
}

func (m *CreateComponentRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type CreateComponentResponse struct {
	Result               *Component `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateComponentResponse) Reset()         { *m = CreateComponentResponse{} }
func (m *CreateComponentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateComponentResponse) ProtoMessage()    {}
func (*CreateComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{11}
}

func (m *CreateComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateComponentResponse.Unmarshal(m, b)
}
func (m *CreateComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateComponentResponse.Marshal(b, m, deterministic)
}
func (m *CreateComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateComponentResponse.Merge(m, src)
}
func (m *CreateComponentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateComponentResponse.Size(m)
}
func (m *CreateComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateComponentResponse proto.InternalMessageInfo

func (m *CreateComponentResponse) GetResult() *Component {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListComponentResponse struct {
	Result               []*Component `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListComponentResponse) Reset()         { *m = ListComponentResponse{} }
func (m *ListComponentResponse) String() string { return proto.CompactTextString(m) }
func (*ListComponentResponse) ProtoMessage()    {}
func (*ListComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{12}
}

func (m *ListComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListComponentResponse.Unmarshal(m, b)
}
func (m *ListComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListComponentResponse.Marshal(b, m, deterministic)
}
func (m *ListComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListComponentResponse.Merge(m, src)
}
func (m *ListComponentResponse) XXX_Size() int {
	return xxx_messageInfo_ListComponentResponse.Size(m)
}
func (m *ListComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListComponentResponse proto.InternalMessageInfo

func (m *ListComponentResponse) GetResult() []*Component {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetTopLevelComponentsByCarModelRequest struct {
	CarModelId           int32    `protobuf:"varint,1,opt,name=car_model_id,json=carModelId,proto3" json:"car_model_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopLevelComponentsByCarModelRequest) Reset() {
	*m = GetTopLevelComponentsByCarModelRequest{}
}
func (m *GetTopLevelComponentsByCarModelRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopLevelComponentsByCarModelRequest) ProtoMessage()    {}
func (*GetTopLevelComponentsByCarModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{13}
}

func (m *GetTopLevelComponentsByCarModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Unmarshal(m, b)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Marshal(b, m, deterministic)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Merge(m, src)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.Size(m)
}
func (m *GetTopLevelComponentsByCarModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopLevelComponentsByCarModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopLevelComponentsByCarModelRequest proto.InternalMessageInfo

func (m *GetTopLevelComponentsByCarModelRequest) GetCarModelId() int32 {
	if m != nil {
		return m.CarModelId
	}
	return 0
}

type GetChildComponentsByComponentRequest struct {
	ParentId             int32    `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChildComponentsByComponentRequest) Reset()         { *m = GetChildComponentsByComponentRequest{} }
func (m *GetChildComponentsByComponentRequest) String() string { return proto.CompactTextString(m) }
func (*GetChildComponentsByComponentRequest) ProtoMessage()    {}
func (*GetChildComponentsByComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{14}
}

func (m *GetChildComponentsByComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChildComponentsByComponentRequest.Unmarshal(m, b)
}
func (m *GetChildComponentsByComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChildComponentsByComponentRequest.Marshal(b, m, deterministic)
}
func (m *GetChildComponentsByComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChildComponentsByComponentRequest.Merge(m, src)
}
func (m *GetChildComponentsByComponentRequest) XXX_Size() int {
	return xxx_messageInfo_GetChildComponentsByComponentRequest.Size(m)
}
func (m *GetChildComponentsByComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChildComponentsByComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetChildComponentsByComponentRequest proto.InternalMessageInfo

func (m *GetChildComponentsByComponentRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type DeleteComponentRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteComponentRequest) Reset()         { *m = DeleteComponentRequest{} }
func (m *DeleteComponentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteComponentRequest) ProtoMessage()    {}
func (*DeleteComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{15}
}

func (m *DeleteComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteComponentRequest.Unmarshal(m, b)
}
func (m *DeleteComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteComponentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteComponentRequest.Merge(m, src)
}
func (m *DeleteComponentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteComponentRequest.Size(m)
}
func (m *DeleteComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteComponentRequest proto.InternalMessageInfo

func (m *DeleteComponentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateComponentRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateComponentRequest) Reset()         { *m = UpdateComponentRequest{} }
func (m *UpdateComponentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateComponentRequest) ProtoMessage()    {}
func (*UpdateComponentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{16}
}

func (m *UpdateComponentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateComponentRequest.Unmarshal(m, b)
}
func (m *UpdateComponentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateComponentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateComponentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateComponentRequest.Merge(m, src)
}
func (m *UpdateComponentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateComponentRequest.Size(m)
}
func (m *UpdateComponentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateComponentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateComponentRequest proto.InternalMessageInfo

func (m *UpdateComponentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateComponentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteComponentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteComponentResponse) Reset()         { *m = DeleteComponentResponse{} }
func (m *DeleteComponentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteComponentResponse) ProtoMessage()    {}
func (*DeleteComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{17}
}

func (m *DeleteComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteComponentResponse.Unmarshal(m, b)
}
func (m *DeleteComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteComponentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteComponentResponse.Merge(m, src)
}
func (m *DeleteComponentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteComponentResponse.Size(m)
}
func (m *DeleteComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteComponentResponse proto.InternalMessageInfo

type UpdateComponentResponse struct {
	Result               *Component `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateComponentResponse) Reset()         { *m = UpdateComponentResponse{} }
func (m *UpdateComponentResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateComponentResponse) ProtoMessage()    {}
func (*UpdateComponentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_885661d4f2172a91, []int{18}
}

func (m *UpdateComponentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateComponentResponse.Unmarshal(m, b)
}
func (m *UpdateComponentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateComponentResponse.Marshal(b, m, deterministic)
}
func (m *UpdateComponentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateComponentResponse.Merge(m, src)
}
func (m *UpdateComponentResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateComponentResponse.Size(m)
}
func (m *UpdateComponentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateComponentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateComponentResponse proto.InternalMessageInfo

func (m *UpdateComponentResponse) GetResult() *Component {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*CarModel)(nil), "api.CarModel")
	proto.RegisterType((*Component)(nil), "api.Component")
	proto.RegisterType((*CreateCarModelRequest)(nil), "api.CreateCarModelRequest")
	proto.RegisterType((*CreateCarModelResponse)(nil), "api.CreateCarModelResponse")
	proto.RegisterType((*GetCarModelByIdRequest)(nil), "api.GetCarModelByIdRequest")
	proto.RegisterType((*GetCarModelResponse)(nil), "api.GetCarModelResponse")
	proto.RegisterType((*ListCarModelsRequst)(nil), "api.ListCarModelsRequst")
	proto.RegisterType((*ListCarModelsResponse)(nil), "api.ListCarModelsResponse")
	proto.RegisterType((*DeleteCarModelRequest)(nil), "api.DeleteCarModelRequest")
	proto.RegisterType((*DeleteCarModelResponse)(nil), "api.DeleteCarModelResponse")
	proto.RegisterType((*CreateComponentRequest)(nil), "api.CreateComponentRequest")
	proto.RegisterType((*CreateComponentResponse)(nil), "api.CreateComponentResponse")
	proto.RegisterType((*ListComponentResponse)(nil), "api.ListComponentResponse")
	proto.RegisterType((*GetTopLevelComponentsByCarModelRequest)(nil), "api.GetTopLevelComponentsByCarModelRequest")
	proto.RegisterType((*GetChildComponentsByComponentRequest)(nil), "api.GetChildComponentsByComponentRequest")
	proto.RegisterType((*DeleteComponentRequest)(nil), "api.DeleteComponentRequest")
	proto.RegisterType((*UpdateComponentRequest)(nil), "api.UpdateComponentRequest")
	proto.RegisterType((*DeleteComponentResponse)(nil), "api.DeleteComponentResponse")
	proto.RegisterType((*UpdateComponentResponse)(nil), "api.UpdateComponentResponse")
}

func init() { proto.RegisterFile("auto_reference_catalog.proto", fileDescriptor_885661d4f2172a91) }

var fileDescriptor_885661d4f2172a91 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xd1, 0x6e, 0xda, 0x30,
	0x14, 0x25, 0xd0, 0xa1, 0x72, 0xb7, 0x82, 0xe4, 0x0a, 0xc8, 0xd2, 0x4e, 0x43, 0xd1, 0xd6, 0x31,
	0x55, 0xe2, 0xa1, 0x7b, 0x9d, 0x56, 0xd1, 0x4c, 0x42, 0xb4, 0x5d, 0x1f, 0xd8, 0xf6, 0x8c, 0xbc,
	0xe4, 0x6e, 0x8d, 0x16, 0xe2, 0xcc, 0x31, 0x95, 0xfa, 0x0d, 0xfb, 0xe9, 0x8a, 0xc4, 0xb1, 0x88,
	0x63, 0xa0, 0xbc, 0x21, 0xdf, 0xe3, 0x73, 0x7c, 0xcf, 0xbd, 0x87, 0xc0, 0x29, 0x5d, 0x0a, 0x36,
	0xe7, 0xf8, 0x1b, 0x39, 0xc6, 0x3e, 0xce, 0x7d, 0x2a, 0x68, 0xc4, 0xfe, 0x8c, 0x12, 0xce, 0x04,
	0x23, 0x0d, 0x9a, 0x84, 0xee, 0x08, 0x0e, 0x3d, 0xca, 0xbf, 0xb1, 0x00, 0x23, 0xd2, 0x86, 0x7a,
	0x18, 0xd8, 0xd6, 0xc0, 0x1a, 0xbe, 0x98, 0xd5, 0xc3, 0x80, 0x10, 0x38, 0x88, 0xe9, 0x02, 0xed,
	0xfa, 0xc0, 0x1a, 0xb6, 0x66, 0xd9, 0x6f, 0x37, 0x86, 0x96, 0xc7, 0x16, 0x09, 0x8b, 0x31, 0x16,
	0xcf, 0xb9, 0x40, 0x06, 0xf0, 0xca, 0xa7, 0x7c, 0xbe, 0x58, 0x29, 0xcc, 0xc3, 0xc0, 0x6e, 0x64,
	0x68, 0xf0, 0xa5, 0xe8, 0x34, 0x20, 0x27, 0xd0, 0x4a, 0x28, 0xc7, 0x58, 0xac, 0xca, 0x07, 0x59,
	0xf9, 0x30, 0x3f, 0x98, 0x06, 0xee, 0x39, 0x74, 0x3d, 0x8e, 0x54, 0x60, 0xf1, 0xca, 0x19, 0xfe,
	0x5b, 0x62, 0x2a, 0x94, 0x96, 0xb5, 0xf6, 0xb8, 0x4b, 0xe8, 0xe9, 0xe0, 0x34, 0x61, 0x71, 0x8a,
	0xe4, 0x3d, 0x34, 0x39, 0xa6, 0xcb, 0x48, 0x64, 0xf8, 0x97, 0x17, 0x47, 0x23, 0x9a, 0x84, 0x23,
	0x05, 0x93, 0x45, 0x77, 0x08, 0xbd, 0x09, 0x8a, 0xe2, 0xf8, 0xea, 0x71, 0x1a, 0x14, 0x72, 0x5a,
	0xab, 0xee, 0x67, 0x38, 0x5e, 0x43, 0xee, 0xab, 0xd3, 0x85, 0xe3, 0xdb, 0x30, 0x55, 0xd7, 0xd3,
	0x95, 0x4a, 0x2a, 0xdc, 0x2f, 0xd0, 0xd5, 0x8e, 0x0d, 0xb4, 0x8d, 0xcd, 0xb4, 0x1f, 0xa0, 0xfb,
	0x15, 0x23, 0xac, 0x9a, 0xa5, 0xbf, 0xde, 0x86, 0x9e, 0x0e, 0xcc, 0x95, 0xdc, 0xbf, 0xca, 0xc2,
	0x62, 0xca, 0x5b, 0x0c, 0xaf, 0x0c, 0xb7, 0xbe, 0xdf, 0x70, 0xc7, 0xd0, 0xaf, 0x88, 0xc9, 0x8e,
	0xcf, 0x34, 0x23, 0xdb, 0x79, 0xc7, 0x0a, 0x57, 0xb4, 0x7c, 0x29, 0x2d, 0xdb, 0x4a, 0xd0, 0xd8,
	0x42, 0x70, 0x0d, 0x67, 0x13, 0x14, 0x3f, 0x58, 0x72, 0x8b, 0x0f, 0x18, 0xa9, 0x7a, 0x7a, 0xf5,
	0xa8, 0x9b, 0xa8, 0x37, 0x6b, 0xe9, 0xcd, 0xba, 0x1e, 0xbc, 0x5b, 0x2d, 0xc5, 0x7d, 0x18, 0x05,
	0x25, 0x22, 0xdd, 0xca, 0x92, 0x29, 0x96, 0x66, 0xca, 0x50, 0xcd, 0x46, 0xbf, 0x56, 0xdd, 0xc1,
	0xde, 0xcf, 0x24, 0xa0, 0xbb, 0x91, 0xc6, 0x24, 0xbf, 0x86, 0x7e, 0x45, 0x47, 0x2e, 0xc1, 0x18,
	0xfa, 0x15, 0xe2, 0xfd, 0xe6, 0x72, 0xf1, 0xbf, 0x09, 0x64, 0xbc, 0x14, 0xcc, 0xcb, 0xff, 0x72,
	0xbe, 0x23, 0x7f, 0x08, 0x7d, 0x24, 0x37, 0xd0, 0x2e, 0x27, 0x94, 0x38, 0x39, 0x81, 0x29, 0xe3,
	0xce, 0x89, 0xb1, 0x26, 0x1f, 0x59, 0x23, 0xd7, 0xd0, 0xd1, 0xd2, 0x4a, 0xf2, 0x1b, 0xe6, 0x0c,
	0x3b, 0xb6, 0x5e, 0x5c, 0xe3, 0x9a, 0xc0, 0x51, 0x29, 0x7a, 0x24, 0x07, 0x1b, 0x52, 0xea, 0x38,
	0xa6, 0x8a, 0x22, 0xba, 0x81, 0x76, 0x39, 0x5a, 0xb2, 0x43, 0x63, 0x30, 0x65, 0x87, 0x1b, 0xb2,
	0x58, 0x23, 0x77, 0xd0, 0xd1, 0x02, 0x42, 0x4a, 0x9e, 0x68, 0x73, 0x77, 0x4e, 0xcd, 0x45, 0xc5,
	0x17, 0xc1, 0xdb, 0x1d, 0xcb, 0x4e, 0xce, 0x0b, 0x93, 0x9e, 0x11, 0x89, 0x75, 0x2b, 0x0c, 0x6a,
	0xf7, 0xf0, 0x66, 0x6b, 0x1c, 0xc8, 0x47, 0x35, 0x90, 0x5d, 0x91, 0xd9, 0xa1, 0x74, 0x07, 0x1d,
	0x6d, 0x97, 0x49, 0xc9, 0x59, 0xb3, 0x4f, 0x9b, 0xd6, 0x3f, 0xe3, 0xd3, 0x02, 0x20, 0xf9, 0xcc,
	0x79, 0x93, 0x7c, 0x1b, 0x32, 0xe3, 0xd6, 0x7e, 0x35, 0xb3, 0x2f, 0xee, 0xa7, 0xa7, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x2e, 0x6a, 0xe9, 0x8a, 0x91, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AutoCatalogServiceClient is the client API for AutoCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AutoCatalogServiceClient interface {
	CreateCarModel(ctx context.Context, in *CreateCarModelRequest, opts ...grpc.CallOption) (*CreateCarModelResponse, error)
	GetCarModelById(ctx context.Context, in *GetCarModelByIdRequest, opts ...grpc.CallOption) (*GetCarModelResponse, error)
	ListCarModels(ctx context.Context, in *ListCarModelsRequst, opts ...grpc.CallOption) (*ListCarModelsResponse, error)
	DeleteCarModel(ctx context.Context, in *DeleteCarModelRequest, opts ...grpc.CallOption) (*DeleteCarModelResponse, error)
	CreateComponent(ctx context.Context, in *CreateComponentRequest, opts ...grpc.CallOption) (*CreateComponentResponse, error)
	GetTopLevelComponentsByCarModel(ctx context.Context, in *GetTopLevelComponentsByCarModelRequest, opts ...grpc.CallOption) (*ListComponentResponse, error)
	GetChildComponentsByComponent(ctx context.Context, in *GetChildComponentsByComponentRequest, opts ...grpc.CallOption) (*ListComponentResponse, error)
	DeleteComponent(ctx context.Context, in *DeleteComponentRequest, opts ...grpc.CallOption) (*DeleteComponentResponse, error)
	UpdateComponent(ctx context.Context, in *UpdateComponentRequest, opts ...grpc.CallOption) (*UpdateComponentResponse, error)
}

type autoCatalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewAutoCatalogServiceClient(cc *grpc.ClientConn) AutoCatalogServiceClient {
	return &autoCatalogServiceClient{cc}
}

func (c *autoCatalogServiceClient) CreateCarModel(ctx context.Context, in *CreateCarModelRequest, opts ...grpc.CallOption) (*CreateCarModelResponse, error) {
	out := new(CreateCarModelResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/CreateCarModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) GetCarModelById(ctx context.Context, in *GetCarModelByIdRequest, opts ...grpc.CallOption) (*GetCarModelResponse, error) {
	out := new(GetCarModelResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/GetCarModelById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) ListCarModels(ctx context.Context, in *ListCarModelsRequst, opts ...grpc.CallOption) (*ListCarModelsResponse, error) {
	out := new(ListCarModelsResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/ListCarModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) DeleteCarModel(ctx context.Context, in *DeleteCarModelRequest, opts ...grpc.CallOption) (*DeleteCarModelResponse, error) {
	out := new(DeleteCarModelResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/DeleteCarModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) CreateComponent(ctx context.Context, in *CreateComponentRequest, opts ...grpc.CallOption) (*CreateComponentResponse, error) {
	out := new(CreateComponentResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/CreateComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) GetTopLevelComponentsByCarModel(ctx context.Context, in *GetTopLevelComponentsByCarModelRequest, opts ...grpc.CallOption) (*ListComponentResponse, error) {
	out := new(ListComponentResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/GetTopLevelComponentsByCarModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) GetChildComponentsByComponent(ctx context.Context, in *GetChildComponentsByComponentRequest, opts ...grpc.CallOption) (*ListComponentResponse, error) {
	out := new(ListComponentResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/GetChildComponentsByComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) DeleteComponent(ctx context.Context, in *DeleteComponentRequest, opts ...grpc.CallOption) (*DeleteComponentResponse, error) {
	out := new(DeleteComponentResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/DeleteComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autoCatalogServiceClient) UpdateComponent(ctx context.Context, in *UpdateComponentRequest, opts ...grpc.CallOption) (*UpdateComponentResponse, error) {
	out := new(UpdateComponentResponse)
	err := c.cc.Invoke(ctx, "/api.AutoCatalogService/UpdateComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutoCatalogServiceServer is the server API for AutoCatalogService service.
type AutoCatalogServiceServer interface {
	CreateCarModel(context.Context, *CreateCarModelRequest) (*CreateCarModelResponse, error)
	GetCarModelById(context.Context, *GetCarModelByIdRequest) (*GetCarModelResponse, error)
	ListCarModels(context.Context, *ListCarModelsRequst) (*ListCarModelsResponse, error)
	DeleteCarModel(context.Context, *DeleteCarModelRequest) (*DeleteCarModelResponse, error)
	CreateComponent(context.Context, *CreateComponentRequest) (*CreateComponentResponse, error)
	GetTopLevelComponentsByCarModel(context.Context, *GetTopLevelComponentsByCarModelRequest) (*ListComponentResponse, error)
	GetChildComponentsByComponent(context.Context, *GetChildComponentsByComponentRequest) (*ListComponentResponse, error)
	DeleteComponent(context.Context, *DeleteComponentRequest) (*DeleteComponentResponse, error)
	UpdateComponent(context.Context, *UpdateComponentRequest) (*UpdateComponentResponse, error)
}

// UnimplementedAutoCatalogServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAutoCatalogServiceServer struct {
}

func (*UnimplementedAutoCatalogServiceServer) CreateCarModel(ctx context.Context, req *CreateCarModelRequest) (*CreateCarModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCarModel not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) GetCarModelById(ctx context.Context, req *GetCarModelByIdRequest) (*GetCarModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCarModelById not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) ListCarModels(ctx context.Context, req *ListCarModelsRequst) (*ListCarModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCarModels not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) DeleteCarModel(ctx context.Context, req *DeleteCarModelRequest) (*DeleteCarModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCarModel not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) CreateComponent(ctx context.Context, req *CreateComponentRequest) (*CreateComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComponent not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) GetTopLevelComponentsByCarModel(ctx context.Context, req *GetTopLevelComponentsByCarModelRequest) (*ListComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopLevelComponentsByCarModel not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) GetChildComponentsByComponent(ctx context.Context, req *GetChildComponentsByComponentRequest) (*ListComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildComponentsByComponent not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) DeleteComponent(ctx context.Context, req *DeleteComponentRequest) (*DeleteComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComponent not implemented")
}
func (*UnimplementedAutoCatalogServiceServer) UpdateComponent(ctx context.Context, req *UpdateComponentRequest) (*UpdateComponentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComponent not implemented")
}

func RegisterAutoCatalogServiceServer(s *grpc.Server, srv AutoCatalogServiceServer) {
	s.RegisterService(&_AutoCatalogService_serviceDesc, srv)
}

func _AutoCatalogService_CreateCarModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCarModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).CreateCarModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/CreateCarModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).CreateCarModel(ctx, req.(*CreateCarModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_GetCarModelById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCarModelByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).GetCarModelById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/GetCarModelById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).GetCarModelById(ctx, req.(*GetCarModelByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_ListCarModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCarModelsRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).ListCarModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/ListCarModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).ListCarModels(ctx, req.(*ListCarModelsRequst))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_DeleteCarModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCarModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).DeleteCarModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/DeleteCarModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).DeleteCarModel(ctx, req.(*DeleteCarModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_CreateComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).CreateComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/CreateComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).CreateComponent(ctx, req.(*CreateComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_GetTopLevelComponentsByCarModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopLevelComponentsByCarModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).GetTopLevelComponentsByCarModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/GetTopLevelComponentsByCarModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).GetTopLevelComponentsByCarModel(ctx, req.(*GetTopLevelComponentsByCarModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_GetChildComponentsByComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildComponentsByComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).GetChildComponentsByComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/GetChildComponentsByComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).GetChildComponentsByComponent(ctx, req.(*GetChildComponentsByComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_DeleteComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).DeleteComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/DeleteComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).DeleteComponent(ctx, req.(*DeleteComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutoCatalogService_UpdateComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutoCatalogServiceServer).UpdateComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AutoCatalogService/UpdateComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutoCatalogServiceServer).UpdateComponent(ctx, req.(*UpdateComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AutoCatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AutoCatalogService",
	HandlerType: (*AutoCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCarModel",
			Handler:    _AutoCatalogService_CreateCarModel_Handler,
		},
		{
			MethodName: "GetCarModelById",
			Handler:    _AutoCatalogService_GetCarModelById_Handler,
		},
		{
			MethodName: "ListCarModels",
			Handler:    _AutoCatalogService_ListCarModels_Handler,
		},
		{
			MethodName: "DeleteCarModel",
			Handler:    _AutoCatalogService_DeleteCarModel_Handler,
		},
		{
			MethodName: "CreateComponent",
			Handler:    _AutoCatalogService_CreateComponent_Handler,
		},
		{
			MethodName: "GetTopLevelComponentsByCarModel",
			Handler:    _AutoCatalogService_GetTopLevelComponentsByCarModel_Handler,
		},
		{
			MethodName: "GetChildComponentsByComponent",
			Handler:    _AutoCatalogService_GetChildComponentsByComponent_Handler,
		},
		{
			MethodName: "DeleteComponent",
			Handler:    _AutoCatalogService_DeleteComponent_Handler,
		},
		{
			MethodName: "UpdateComponent",
			Handler:    _AutoCatalogService_UpdateComponent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auto_reference_catalog.proto",
}
