// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CarModel struct {
	ID   int64
	Name string
}

type Component struct {
	ID         int64
	Name       string
	CarModelID pgtype.Int4
	ParentID   pgtype.Int4
}
